//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alivio_UI_Mockup {
    
    
    public partial class Funds {
        
        /// <summary>
        /// modalChangeCycle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Alivio_UI_Mockup.UserContols.modalChangeCycle modalChangeCycle;
    }
}
